version: '3.8'

services:
  client-processing:
    build:
      context: .
      dockerfile: Dockerfile-client
    container_name: client-processing
    ports:
      - "8081:8081"
    networks:
      - bank-network
    restart: unless-stopped

  account-processing:
    build:
      context: .
      dockerfile: Dockerfile-account
    container_name: account-processing
    ports:
      - "8082:8082"
    networks:
      - bank-network
    restart: unless-stopped

  credit-processing:
    build:
      context: .
      dockerfile: Dockerfile-credit
    container_name: credit-processing
    ports:
      - "8083:8083"
    networks:
      - bank-network
    restart: unless-stopped
  
  zookeeper:
      image: confluentinc/cp-zookeeper:7.4.0
      environment:
        ZOOKEEPER_CLIENT_PORT: 2181
        ZOOKEEPER_TICK_TIME: 2000
      ports:
        - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_DELETE_TOPIC_ENABLE: "true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  bank-network:
    driver: bridge